### ISSUE TITLE
EN : Article can not be created

### ISSUE THREAD

**Issue by Anthere** [offspot/wikifundi#107]
the process is going nowhere after the content is created and we click on the save button.

**Comment by rgaudin** [comment]
I'm getting this:
<img width="530" alt="Screen Shot 2021-09-14 at 09 10 14" src="https://user-images.githubusercontent.com/57929/133230122-52a0a612-eab1-483b-b2e5-0a4c6b3bb3f2.png">

This is due to the _limited_ resources of the online mirrors. Works fine locally and on the Pi.

I suppose you just wanted to ensure creating articles works. Please reopen if you need to create an article online or if you were getting something different.

**Comment by Anthere** [comment]
Yes, this is the type of message I get. I was simply testing page creation.
