### ISSUE TITLE
En : Springbok not imported

### ISSUE THREAD

**Issue by Anthere** [offspot/wikifundi#111]
In the http://wikifundi-en.openzim.org/wiki/Wikipedia:Showcase, the Springbox article has not been imported. 

I could not figure out why....

**Comment by rgaudin** [comment]
Well, the [Baleen Whale](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_WikiFundi_Content/Baleen_whale) article is copied inside the Project while [Springbok](https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_WikiFundi_Content/springbok&redirect=no) is a redirection to https://en.wikipedia.org/wiki/Springbok. As we remove the `Wikipedia:WikiProject_WikiFundi_Content/` prefix, that might be an issue.

As all the other ones have been copied, I advise you copy this one as well instead of the redirection.

**Comment by Anthere** [comment]
done
