### ISSUE TITLE
ES : resources not displayed properly for audio 

### ISSUE THREAD

**Issue by Anthere** [offspot/wikifundi#117]
On this page, at the bottom, the audio resources are displayed wrongly

**Comment by rgaudin** [comment]
I suppose we're talking about http://wikifundi-es.openzim.org/wiki/WikiAfrica_Offline_Resources/es
<img width="1150" alt="Screen Shot 2021-09-21 at 11 08 44" src="https://user-images.githubusercontent.com/57929/134160361-a9d3f9c1-9a03-4055-a232-e5c59f6abd33.png">

**Comment by rgaudin** [comment]
This is actually linked to #72. The problem is that the file has a `?` character in it. It works fine for accessing the file but the thumbnailing, which uses an external program doesn't work as expected. Upstream solution for #72 did not work so what I suggest in the mean time is to rename those 3 files to remove the `?` and change the link. Doing that now.
